### ISSUE TITLE
forge-fabric-quilt-mixin templates are broken for Quilt

### ISSUE THREAD

**Issue by Urkaz** [architectury/architectury-templates#30]
The template "*-forge-fabric-quilt-mixin" is broken when running it for Quilt without doing any modifications.

It crashes because it tries to load the common mixins from the quilt folder instead of using the common folder:

```
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: C:\1.20.1-forge-fabric-quilt-mixin\quilt\build\resources\main\examplemod-common.mixins.json
	at org.quiltmc.loader.impl.transformer.TransformCache.extractRefmap(TransformCache.java:214) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCache.<init>(TransformCache.java:85) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCacheGenerator.generate(TransformCacheGenerator.java:45) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.writeTransformCache(TransformCacheManager.java:287) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.createTransformCache(TransformCacheManager.java:260) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.populateTransformBundle(TransformCacheManager.java:100) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:375) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:304) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) ~[dev-launch-injector-0.2.1+build.8.jar:?]
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219) ~[architectury-transformer-5.2.83-runtime.jar:5.2.83]
Caused by: java.nio.file.NoSuchFileException: C:\1.20.1-forge-fabric-quilt-mixin\quilt\build\resources\main\examplemod-common.mixins.json
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2922) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2955) ~[?:?]
	at org.quiltmc.loader.impl.lib.parsers.json.JsonReader.<init>(JsonReader.java:353) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.lib.parsers.json.JsonReader.json(JsonReader.java:319) ~[quilt-loader-0.21.2-beta.2.jar:?]
	at org.quiltmc.loader.impl.transformer.TransformCache.extractRefmap(TransformCache.java:203) ~[quilt-loader-0.21.2-beta.2.jar:?]
```

Steps:

* Download a template containnig "forge-fabric-quilt-mixin" (1.20.1-forge-fabric-quilt-mixin,zip for example).
* Open the template and run Quilt client.
* Notice the crash.

**Comment by rinOfTheStars** [comment]
This actually happens with _all_ common resources at runtime (`runClient`/`runServer`) regardless of loader; forge appears to work fine only because loom is handling copying the common mixin json
